; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:MatterControllerRGB]
platform = https://github.com/pioarduino/platform-espressif32.git 
; https://docs.platformio.org/en/latest/platforms/espressif32.html#using-arduino-framework-with-staging-version
; Try this ^ at some point down the road. 
board = esp32_s3_matter_rgb
framework = arduino
board_build.mcu = esp32s3
; board_build.f_cpu = 240000000L
board_build.usb_mode = cdc
board_build.usb_product = "ESP32-S3 USB CDC"
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
upload_protocol = esptool
monitor_speed = 115200
lib_deps = kcl93/FUSB302 PD UFP sink@^0.1
; upload_protocol = espota
; upload_port = 192.168.20.37
; upload_flags =
;     --port=3232